plugins {
    id 'java-library'
}

repositories {
    mavenCentral()
}

java {
    withSourcesJar()
    withJavadocJar()
}

sourceSets {
    main {
        java {
            srcDir '../api/src/main/java'
        }
    }
}

dependencies {
    api 'com.google.auto.service:auto-service-annotations:1.1.1'
    annotationProcessor 'com.google.auto.service:auto-service:1.1.1'
    implementation 'com.squareup:javapoet:1.13.0'
}