plugins {
    id 'java-library'
    id 'maven-publish'
    id 'idea'
    id 'net.neoforged.moddev' version '2.0.140'
}

repositories {
    mavenLocal()
    maven {
        name = "AC Dev Team's maven"
        //url = uri("D:/Project/maven-repo")
        url = uri("https://raw.githubusercontent.com/AcademyCraft-Dev-Team/maven-repo/master/")
        content {
            includeGroup("org.academy")
            includeGroup("net.neoforged")
        }
    }
}

base {
    version = mod_version
    group = mod_group_id
    archivesName = "misaka-network"
}

java {
    withSourcesJar()
    withJavadocJar()
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [minecraft_version      : minecraft_version,
                             minecraft_version_range: minecraft_version_range,
                             neo_version            : neo_version,
                             neo_version_range      : neo_version,
                             mod_id                 : mod_id,
                             mod_name               : mod_name,
                             mod_license            : mod_license,
                             mod_version            : mod_version,
                             mod_authors            : mod_authors,
                             mod_description        : mod_description]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets {
    main {
        resources.srcDir generateModMetadata
        java {
            srcDir '../api/src/main/java'
        }
    }
}

neoForge {
    version = project.neo_version
    ideSyncTask generateModMetadata
    runs {
        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        server {
            server()
            programArgument '--nogui'
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        gameTestServer {
            type = "gameTestServer"
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }
    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }
}

dependencies {
    implementation project(':processor')
    annotationProcessor project(':processor')
    annotationProcessor("com.google.auto.service:auto-service:1.1.1")
}

tasks.named('jar', Jar) {
    archiveClassifier.set('')

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from sourceSets.main.output
    from(sourceSets.main.resources)
    from project(':processor').sourceSets.main.output

    from {
        project(':processor').configurations.runtimeClasspath.files.collect {
            if (it.isDirectory()) {
                it
            } else {
                zipTree(it).matching {
                    exclude 'META-INF/maven/**'
                }
            }
        }
    }
}

tasks.named('sourcesJar', Jar) {
    from project(':processor').sourceSets.main.allJava
}

publishing {
    publications {
        create('mavenJava', MavenPublication) {
            groupId = 'org.academy'
            artifactId = 'misaka-network'

            artifact tasks.named('jar')
            artifact tasks.named('sourcesJar')
            artifact tasks.named('javadocJar')
        }
    }
    repositories {
        maven {
            url = uri('D:/Project/maven-repo')
        }
    }
}

idea {
    module {
        var generatedSourceDir = file("build/generated/sources/annotationProcessor/java/main")
        sourceDirs += generatedSourceDir
        generatedSourceDirs += generatedSourceDir
        downloadSources = true
        downloadJavadoc = true
    }
}